version: '3.7'
services:

  # PHP api
  app:
    build:
      context: .
      dockerfile: config/Dockerfile
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    ports:
      - 8080:8080
    container_name: php_api
    volumes:
      - .:/var/www

  # MySQL database server
  mysql:
    image: mysql
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=test-db

volumes:
  db-data: